lib/tech_interview_web/router.ex
defmodule TechInterviewWeb.Router do
  use TechInterviewWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TechInterviewWeb do
    pipe_through :browser

    get "/", CompanyController, :index

    resources "/register", UserController, only: [:create, :new]
    resources "/companies", CompanyController, only: [:show, :index]
    resources "/questions", QuestionController, except: [:delete]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TechInterviewWeb do
  #   pipe_through :api
  # end
end

lib/tech_interview_web/views/layout_view.ex
defmodule TechInterviewWeb.LayoutView do
  use TechInterviewWeb, :view
end

lib/tech_interview_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Tech Interview</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <nav class="flex items-center justify-between flex-wrap bg-gray-800 p-6">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
          <span class="font-bold text-xl">Tech Interview</span>
        </div>

        <div class="w-full block flex-grow sm:flex sm:items-center sm:w-auto">
          <div class="text-sm sm:flex-grow">
            <%= link "Companies", to: Routes.company_path(@conn, :index), class: "block mt-4 sm:inline-block sm:mt-0 text-teal-200 hover:text-white mr-4" %>
            <%= link "Questions", to: Routes.question_path(@conn, :index), class: "block mt-4 sm:inline-block sm:mt-0 text-teal-200 hover:text-white mr-4" %>
          </div>
          <div>
            <%= if signed_in?(@conn) do %>
              <%= link "Sign out", to: Routes.session_path(@conn, :delete), method: :delete, class: 'inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 md:mt-0' %>
            <% else %>
              <%= link "Sign In", to: Routes.session_path(@conn, :new), class: 'inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 md:mt-0' %>
              |
              <%= link "Sign up", to: Routes.user_path(@conn, :new), class: 'inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 md:mt-0' %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <main role="main">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>